### ISSUE TITLE
Page refreshes automatically after retrieving results

### ISSUE THREAD

**Issue by matheusft** [aCampello/sponsors-search#3] opened 2021-08-06 12:35 UTC
Try [searching](https://antoniocampello.com/sponsors-search/?) for Apple.
It returns the results and quickly refreshed the page so you don't have time to see the results.

**Comment by aCampello** [comment] 2021-08-06 12:44
Thanks for the issue Matheus. Can you confirm what’s your browser and/or try another browser ? It works for me on chrome.

I have to update this app anyway because now we have he raw csvs on the HO webpage, so will try to fix your issue too.

**Comment by matheusft** [comment] 2021-08-06 12:46
I see the bug on both browsers:
Chrom Version 92.0.4515.131
Safari Version 14.1.1

**Comment by aCampello** [comment] 2021-08-06 12:52
Cool, I reproduced here, will fix :). In the meantime maybe you can use the csv! Thanks for the issue.

**Comment by aCampello** [comment] 2022-03-15 22:58
This was fixed in the new version!

**Closed by aCampello** 2022-03-15 22:58 UTC
Labels: bug
